(() => {
    'use strict';
    const trips = [
    {
        "id": "2026-08-01-1",
        "date": "2026-08-01",
        "course": "半夜便",
        "time": "18:00",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-01-2",
        "date": "2026-08-01",
        "course": "深夜便（中型船）",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "第二豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 9,
        "remaining": 3,
        "status": "few",
        "price": 13000
    },
    {
        "id": "2026-08-02-1",
        "date": "2026-08-02",
        "course": "半夜便",
        "time": "18:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 9,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-02-2",
        "date": "2026-08-02",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-03-1",
        "date": "2026-08-03",
        "course": "半夜便",
        "time": "18:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 12,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-03-2",
        "date": "2026-08-03",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-04-1",
        "date": "2026-08-04",
        "course": "半夜便",
        "time": "18:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 5,
        "remaining": 11,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-04-2",
        "date": "2026-08-04",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-05-1",
        "date": "2026-08-05",
        "course": "半夜便",
        "time": "18:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 8,
        "remaining": 8,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-05-2",
        "date": "2026-08-05",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-06-1",
        "date": "2026-08-06",
        "course": "半夜便",
        "time": "18:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 11,
        "remaining": 5,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-06-2",
        "date": "2026-08-06",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-07-1",
        "date": "2026-08-07",
        "course": "半夜便",
        "time": "18:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 14,
        "remaining": 2,
        "status": "few",
        "price": 13000
    },
    {
        "id": "2026-08-07-2",
        "date": "2026-08-07",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 9,
        "remaining": 3,
        "status": "few",
        "price": 13000
    },
    {
        "id": "2026-08-08-1",
        "date": "2026-08-08",
        "course": "半夜便",
        "time": "18:00",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-09-1",
        "date": "2026-08-09",
        "course": "半夜便",
        "time": "18:00",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-09-2",
        "date": "2026-08-09",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 12,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-10-1",
        "date": "2026-08-10",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-10-2",
        "date": "2026-08-10",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 12,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-11-1",
        "date": "2026-08-11",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-12-1",
        "date": "2026-08-12",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-13-1",
        "date": "2026-08-13",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-14-1",
        "date": "2026-08-14",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-15-1",
        "date": "2026-08-15",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 16,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-16-1",
        "date": "2026-08-16",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 11,
        "remaining": 5,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-16-2",
        "date": "2026-08-16",
        "course": "特別便",
        "time": "18:30",
        "target": "船から花火大会",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 10,
        "reserved": 10,
        "remaining": 0,
        "status": "full",
        "price": 13000
    },
    {
        "id": "2026-08-17-1",
        "date": "2026-08-17",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 4,
        "remaining": 12,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-17-2",
        "date": "2026-08-17",
        "course": "深夜便",
        "time": "－",
        "target": "－",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 0,
        "remaining": 0,
        "status": "unknown",
        "price": 13000
    },
    {
        "id": "2026-08-18-1",
        "date": "2026-08-18",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 7,
        "remaining": 9,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-18-2",
        "date": "2026-08-18",
        "course": "深夜便",
        "time": "－",
        "target": "－",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 0,
        "remaining": 0,
        "status": "unknown",
        "price": 13000
    },
    {
        "id": "2026-08-19-1",
        "date": "2026-08-19",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 10,
        "remaining": 6,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-19-2",
        "date": "2026-08-19",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-20-1",
        "date": "2026-08-20",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 3,
        "remaining": 13,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-20-2",
        "date": "2026-08-20",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-21-1",
        "date": "2026-08-21",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 6,
        "remaining": 10,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-21-2",
        "date": "2026-08-21",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-22-1",
        "date": "2026-08-22",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 14,
        "remaining": 2,
        "status": "few",
        "price": 13000
    },
    {
        "id": "2026-08-23-1",
        "date": "2026-08-23",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 12,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-23-2",
        "date": "2026-08-23",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-24-1",
        "date": "2026-08-24",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 5,
        "remaining": 11,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-24-2",
        "date": "2026-08-24",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-25-1",
        "date": "2026-08-25",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 8,
        "remaining": 8,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-25-2",
        "date": "2026-08-25",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-26-1",
        "date": "2026-08-26",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 11,
        "remaining": 5,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-26-2",
        "date": "2026-08-26",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-27-1",
        "date": "2026-08-27",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 4,
        "remaining": 12,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-27-2",
        "date": "2026-08-27",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-28-1",
        "date": "2026-08-28",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 7,
        "remaining": 9,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-28-2",
        "date": "2026-08-28",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-29-1",
        "date": "2026-08-29",
        "course": "半夜便",
        "time": "17:30",
        "target": "スーパーロング便",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 13,
        "remaining": 3,
        "status": "few",
        "price": 13000
    },
    {
        "id": "2026-08-30-1",
        "date": "2026-08-30",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 3,
        "remaining": 13,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-30-2",
        "date": "2026-08-30",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-31-1",
        "date": "2026-08-31",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 6,
        "remaining": 10,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-08-31-2",
        "date": "2026-08-31",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-01-1",
        "date": "2026-09-01",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 6,
        "remaining": 10,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-01-2",
        "date": "2026-09-01",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-02-1",
        "date": "2026-09-02",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 9,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-02-2",
        "date": "2026-09-02",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-03-1",
        "date": "2026-09-03",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 12,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-04-1",
        "date": "2026-09-04",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 5,
        "remaining": 11,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-04-2",
        "date": "2026-09-04",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-05-1",
        "date": "2026-09-05",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 16,
        "reserved": 8,
        "remaining": 8,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-05-2",
        "date": "2026-09-05",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 12,
        "reserved": 5,
        "remaining": 7,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-06-1",
        "date": "2026-09-06",
        "course": "半夜便",
        "time": "17:30",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "佐藤船長",
        "capacity": 16,
        "reserved": 11,
        "remaining": 5,
        "status": "ok",
        "price": 13000
    },
    {
        "id": "2026-09-06-2",
        "date": "2026-09-06",
        "course": "深夜便",
        "time": "22:00",
        "target": "マイカ＆ムギイカ",
        "ship": "豊漁丸",
        "captain": "山田船長",
        "capacity": 12,
        "reserved": 8,
        "remaining": 4,
        "status": "ok",
        "price": 13000
    }
    ];

    const OVERRIDE_KEY = 'horyomaruTripReservationDelta';
    const readOverrides = () => {
        try { return JSON.parse(localStorage.getItem(OVERRIDE_KEY) || '{}') || {}; } catch { return {}; }
    };
    const statusFromSeats = (trip) => {
        const contentReady = !['', '－', '-', '未定', '内容未定'].includes(String(trip.time || '').trim())
        && !['', '－', '-', '未定', '内容未定'].includes(String(trip.target || '').trim());
        if (!contentReady) return 'unknown';
        const remaining = Math.max(0, Number(trip.capacity || 0) - Number(trip.reserved || 0));
        if (remaining === 0) return 'full';
        if (remaining <= 3) return 'few';
        return 'ok';
    };

    const enrich = (trip) => {
        const copy = { ...trip };
        const overrides = readOverrides();
        copy.reserved = Math.min(Number(copy.capacity || 0), Number(copy.reserved || 0) + Number(overrides[copy.id] || 0));
        copy.remaining = Math.max(0, Number(copy.capacity || 0) - Number(copy.reserved || 0));
        copy.status = statusFromSeats(copy);
        return copy;
    };

    const getTrips = () => trips.map(enrich);
    const getTrip = (date, course) => getTrips().find((trip) => trip.date === date && trip.course === course) || null;

    // 管理画面用の予約明細を、各便の予約人数と合計が一致するように生成する。
    const names = [
    ['田中 太郎','たなか たろう'],['佐藤 花子','さとう はなこ'],['鈴木 一郎','すずき いちろう'],
    ['高橋 美咲','たかはし みさき'],['伊藤 健','いとう けん'],['山本 彩','やまもと あや'],
    ['中村 翔','なかむら しょう'],['小林 葵','こばやし あおい'],['加藤 蓮','かとう れん'],['吉田 凛','よしだ りん']
    ];
    const reservations = [];
    trips.forEach((trip, tripIndex) => {
        let rest = Number(trip.reserved || 0);
        let bookingIndex = 0;
        while (rest > 0) {
            const participants = Math.min(rest, 1 + ((tripIndex + bookingIndex) % 4));
            const person = names[(tripIndex + bookingIndex) % names.length];
            const serial = String(1000 + tripIndex * 10 + bookingIndex);
            reservations.push({
                id: `R-${serial}`, tripId: trip.id, date: trip.date.replaceAll('-', '/'), dateKey: trip.date,
                course: trip.course, name: person[0], nameKana: person[1], participants,
                rentalRod: (tripIndex + bookingIndex) % 3 === 0 ? 1 : 0,
                phone: `090-${String(1200 + ((tripIndex + bookingIndex) % 7000)).padStart(4,'0')}-${String(3000 + ((tripIndex*7 + bookingIndex) % 6000)).padStart(4,'0')}`,
                email: `guest${serial}@example.com`, status: trip.date < '2026-08-06' ? '乗船済み' : '予約中'
            });
            rest -= participants;
            bookingIndex += 1;
        }
    });

    const addReservationDelta = (tripId, participants) => {
        const overrides = readOverrides();
        overrides[tripId] = Number(overrides[tripId] || 0) + Number(participants || 0);
        localStorage.setItem(OVERRIDE_KEY, JSON.stringify(overrides));
    };
    window.HoryomaruAppData = { getTrips, getTrip, addReservationDelta, reservations: reservations.map((item) => ({...item})) };
})();
